### ISSUE TITLE
Events test panics sometimes

### ISSUE THREAD

**Issue by ParadoxSpiral** [ParadoxSpiral/mpv-rs#4]
```
unning 3 tests
test tests::version ... ok
test tests::properties ... ok
test tests::events_simple ... FAILED
failures:
---- tests::events_simple stdout ----
    thread 'tests::events_simple' panicked at 'assertion failed: !ptr.is_null()', src/wrapper/events/events_simple.rs:42:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:217
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:365
   6: mpv::wrapper::events::events_simple::PropertyData::from_raw
             at src/wrapper/events/events_simple.rs:42
   7: mpv::wrapper::events::events_simple::<impl mpv::wrapper::Mpv>::wait_event::{{closure}}
             at src/wrapper/events/events_simple.rs:254
   8: <core::result::Result<T, E>>::and_then
             at /checkout/src/libcore/result.rs:621
   9: mpv::wrapper::events::events_simple::<impl mpv::wrapper::Mpv>::wait_event
             at src/wrapper/events/events_simple.rs:251
  10: mpv::tests::events_simple
             at src/tests.rs:155
  11: mpv::__test::TESTS::{{closure}}
             at src/tests.rs:83
  12: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:783
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
failures:
    tests::events_simple
test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by ParadoxSpiral** [comment]
Seems to have been fixed in the new libmpv.
